version: '3.8'

services:
  posts_servise:
    container_name: posts_servise
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    environment:
      - PRODUCTION=true
      - APP_PORT=$APP_PORT
    ports:
      - ${APP_PORT}:${APP_PORT}